services:
    views_counter.visitable_manager:
        class: Lavulator\ViewsCounterBundle\Manager\VisitableManager
        arguments: ["@doctrine.orm.entity_manager"]
        public: true

    views_counter.views_counter:
        class: Lavulator\ViewsCounterBundle\Manager\SessionViewsCounter
        arguments: ["@session", "@views_counter.visitable_manager"]
        public: true

    views_counter.cookie_views_counter:
        class: Lavulator\ViewsCounterBundle\Manager\CookieViewsCounter
        arguments: ["@session", "@views_counter.visitable_manager"]
        public: true